### ISSUE TITLE
[Feature] Data in the descriptor 

### ISSUE THREAD

**Issue by kk5dire** [Tech-TTGames/Tickets-Plus#22]
**Description**
Contain some brief, yet important, ticket info in the descriptor of the ticket. 
Some ex. Info: 

- The UID of the ticket invoker and username+discrim
- The creation date of the ticket
- The date the ticket will be autoclosed (using discord's timestamp format) perhaps could even be updated/reset when messages are sent [of course only including the date, if the case. As to not cause rate limits].
- Perhaps if/when #17 would be implemented, include this in this field. 

**Reason this would be helpful?**
Because, knowledge is power- *Au combat, mes soldats!*

**Comment by Tech-TTGames** [comment]
Prolly in next build.

**Comment by Tech-TTGames** [comment]
Update: There is currently no universal way to get the ticket opener. So I'm putting this request on hold. May log the creation date of ticket thou!

**Comment by Tech-TTGames** [comment]
Will be expanded in v0.1.0.1

**Comment by Tech-TTGames** [comment]
Will be later expanded on but will be closed with this PR.
