### ISSUE TITLE
[Tool] Join thread

### ISSUE THREAD

**Issue by kk5dire** [Tech-TTGames/Tickets-Plus#23]
**Description**
A command to join the private thread, (if the user was not already added on initialization) 

**Reasoning** 
This would be useful for users of correct permissions to add themselves to the thread without requiring a @mention on thread initialization.
Would be good for separation between invoker and @mention roles.

**Comment by Tech-TTGames** [comment]
An idea that I can implement witout v0.1 wow! Good idea tho.

**Comment by kk5dire** [comment]
To add, IMO responses from bot should be ephemeral, so the user doesn't know who's gossiping about them

Great way to get around pinging people IMO

**Comment by Tech-TTGames** [comment]
Yea but ping can still be there for people who want it.

**Comment by Tech-TTGames** [comment]
Do your role stuff on r/google or something.

**Comment by benfoster04** [comment]
Is it too much to ask for that users who wish to access the notes thread just.. go to the channel, hover over it, and click on the notes thread to join it? Although I do agree with @kk5dire, a ephemeral slash command could be in order to take care of this.

**Comment by Tech-TTGames** [comment]
> Is it too much to ask for that users who wish to access the notes thread just.. go to the channel, hover over it, and click on the notes thread to join it? Although I do agree with @kk5dire, a ephemeral slash command could be in order to take care of this.

The notes are a private thread. So any users without manage threads permissions and not added to thread cannot see it.

I'll make the command _sometime._

**Comment by kk5dire** [comment]
> Do your role stuff on r/google or something.

Jusstttt waiting for all the cogs to be in place

**Comment by kk5dire** [comment]
@Tech-TTGames should have linked PR #34 to this, but whoopsies <shrug>

**Comment by Tech-TTGames** [comment]
It *was* linked. CodeQL was just taking it's sweet time.

**Comment by kk5dire** [comment]
> It _was_ linked. CodeQL was just taking it's sweet time.

Didn't show as linked for me, also yeah, CodeQL was taking a while

**Comment by Tech-TTGames** [comment]
> > It _was_ linked. CodeQL was just taking it's sweet time.
> 
> Didn't show as linked for me, also yeah, CodeQL was taking a while

Any issues mentioned in PR's are auto-closed

**Comment by kk5dire** [comment]
Should have closed without QL iirc, Wasn't directly linked via proj
