### ISSUE TITLE
[Feature]: Show who opened a shushed ticket

### ISSUE THREAD

**Issue by xJustxMegx** [Tech-TTGames/Tickets-Plus#46]
### Summary

A option to show who open a shushed so we eventually can take action if they abuse it.

### Feature Description

Hello,

When you open a normal ticket using the Tech Support Channel - which most users do - you can see who opened a ticket and that makes it easier to give direct support to the user.
![image](https://user-images.githubusercontent.com/7931828/224477865-3457c6c8-feb5-4f1d-a2e9-17a5d72a7b45.png)

People of the Tech Team can open a ticket without mentioning anyone but you can not see who opened this ticket by default -or as normal user - so would it be possible to include this in the private thread, channel or description?
![image](https://user-images.githubusercontent.com/7931828/224477962-3af23ea1-2adf-4d29-b4f5-69263f5b19af.png)

This way we can avoid eventually abuse and inform users more direct about the fact that using a shushed ticket is not for the way they do it.

### Justification

Do I need to write my whole story here again? That's dumb.

### Additional Context

Why requires this also context, I have nothing to share.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tech-TTGames** [comment]
*pfft*
Invalid: Just edit the open message from Tickets bot.

**Comment by Tech-TTGames** [comment]
Off-topic. Use r/google staff chat.
