### ISSUE TITLE
[Enhancement]: Actual Tickets Integration

### ISSUE THREAD

**Issue by Tech-TTGames** [Tech-TTGames/Tickets-Plus#47]
### Summary

The feature of future! We will actually get data from the main Tickets. Bot involves another whole batch of annoyances and so is planned for v0.1.1.

### Description

Basically we will have to make an API for the Tickets bot to send POST requests to.
We would then get this great package:
{
  "guild_id": "508392876359680000",
  "user_id": "585576154958921739",
  "ticket_id": 123,
  "ticket_channel_id": "508410703439462400"
}

### The Basis

This would remove the need for ticket users and change the mechanism based on which we run our opening actions. Making the code more reliable for the intents and purposes.

### Use Case

We can get user_id reliably. As it currently stands we have no practical way for doing so.

### Impact

A lot of work. Reliability. Less setup? They would have to add the integration on panel.ticketsbot.net

### Alternatives

The one is currently in use yes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tech-TTGames** [comment]
But I'm probably gonna have a stroke writing an API to add to all of this
So delayed

**Comment by kk5dire** [comment]
GL with this when you get to it, i'm sure its going to be one hell of an update
