### ISSUE TITLE
Ticket Checkup

### ISSUE THREAD

**Issue by Hydraulisch** [Tech-TTGames/Tickets-Plus#5]
"So currently you can either have auto-close on inactivity or no-autoclose.
Both has pros and cons.

But how about auto-closerequest?
After x hours there will be a prompt similar to the one from closerequest "has your issue been solved?"
- Keyinator

What if Tickets+ added a way to ask the question "has your issue been solved", if the user responds with No, then the bot will ping a certain role. if the user says yes, it'll close the the ticket in 5mins with warning

**Comment by Tech-TTGames** [comment]
Impossible to add via external bot unless Ryan adds a way for integrations to close tickets. 
Bots can't interact with bots.
