### ISSUE TITLE
[Feature]: Silent Tags

### ISSUE THREAD

**Issue by kk5dire** [Tech-TTGames/Tickets-Plus#50]
### Summary

A tag without the direct reply to the command invoker. 

### Feature Description

A tag that trusted support members could use to provide information to the end user without particularly revealing themselves as the command invoker. 

### Justification

This would be useful for informative messages that can be used by moderators and trusted support team members to provide information to other users, to either inform users about something, or to help stop the spread of misinformation in tickets. 

***TLDR***
- Would be useful for information
- Would be useful to stop misinformation
- A command for trusted support/moderators

### Additional Context

I feel this would be a great help with moderation as it acts as a way to help stop the spread of misinformation, provide information, etc. Without specifically calling attention to a moderator or trusted support member. Would be like the anon reply `/respond` command but would contain canned content like the `/tag` command featured in the base bot. 

***Drawbacks***
- Would need DB storage 
- Perhaps would be too ambitious to expect anytime soon

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tech-TTGames** [comment]
Basic text-style tags wouldn't be that hard. A bit harder to accommodate for embed ones.
