### ISSUE TITLE
[Enhancement]: Styling Adjustment for pages

### ISSUE THREAD

**Issue by kk5dire** [Tech-TTGames/Tickets-Plus#52]
### Summary

Improve the styling of pages by Adjusting the colour theme to more better fit those who lurk on their computers at night. 

### Description

- Change the Pages enviro theme to be darker/night themed

### The Basis

So users don't blind themselves when they are looking at the Pages Enviro in their dusty old basements at night, while the children scream for help in the background. 

### Use Case

It's just pure science my man! 

### Impact

It would allow the future generations to live in peace knowing that their children's eyes are safe from unholy webpages. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tech-TTGames** [comment]
FYI v0.1 will introduce probably moving the pages to a directory and using pydoc.

**Comment by kk5dire** [comment]
> Referenc

Anything is better than what there is now
