### ISSUE TITLE
[Enhancement]: Toggleable Anonymous Messages

### ISSUE THREAD

**Issue by Hydraulisch** [Tech-TTGames/Tickets-Plus#9]
Using /anonymous on/off will turn the ticket (per ticket, not every ticket) into a fully anonymous ticket, allowing staff to just type anonymous sentences without /respond.

**Comment by Tech-TTGames** [comment]
Good feature request however I won't implement it till I get multi-server configuration which means a switch from .json to a PostgreSQL or SQLite.

**Comment by Tech-TTGames** [comment]
Possible [stupid] solution to the issue without db. Edit channel description and keep some data for flags there
